### ISSUE TITLE
setup.py install failed

### ISSUE THREAD

**Issue by TBetterman** [princeton-vl/DROID-SLAM#20] opened 2021-11-12 13:51 UTC
Hi, when i run **python setup.py install**, the compile error happened: **TypeError: expected string or bytes-like object**

Python version: 3.8
setuptools version: 50.3.0

![image](https://user-images.githubusercontent.com/12430411/141477443-991892cf-2f21-43ef-a5be-38d472db3ea2.png)

Please give some advice if convenient, thanks.

**Comment by cuge1995** [comment] 2021-11-14 13:16
same problem

**Comment by snehahegdek** [comment] 2021-11-15 06:52
I'm having the same problem.

**Comment by TBetterman** [comment] 2021-11-15 08:00
Hi, all, I have solved this problem @cuge1995 @snehahegdek :
- open the cooresponding **version.py**
- Changed the code on line 200 from **match = self._regex.search(version)** to **match = self._regex.search(str(version))**
- re-ran the code: **python setup.py install**

Enjoy!

**Comment by Nekomiya-fubuki** [comment] 2021-11-16 12:15
@TBetterman Hi,Can I ask a question?How can I open the cooresponding version.py.I can't find this program  erverywhere in the file.

**Comment by doomzzju** [comment] 2021-11-22 02:05
try python3 instead, man

**Comment by zachteed** [comment] 2021-11-30 03:37
This issue seemed to be caused by the PyTorch update. I've updated the environment.yaml file, which I believe solves the issue.

**Comment by Sabrinashurong** [comment] 2022-01-19 08:11
if one of the previous errors in the cuda compilation is "nvcc fatal   : Unsupported gpu architecture 'compute_80' \n ninja: build stopped: subcommand failed."the following solution may work. This is because that the mismatch between the expected computation power assignement in `setup.py` between the actual power in your computer.  So, if your computer gpu is RTX 2080 ti, the computation power parameters 8.0 and 8.6 can not be achieved. So, the solution of commenting the following lines (line 25, 26, 55, 56) in the `setup.py` may work.
```
#'-gencode=arch=compute_80,code=sm_80',
#'-gencode=arch=compute_86,code=sm_86',
```

**Comment by Mikhail2017** [comment] 2024-02-20 21:59
It could be also connected to the cpu version of torch package installed using environment.yaml. I was not able to install environment using conda, because it hanged on the resolving stage and used mamba instead, unfortunately it led to the incorrect package wo cuda support. Solved it finally installing all the packages separately using both conda and pip

**Closed** 2024-03-05 13:10 UTC
